//! Phase 3 — export to the repository a decision governs (D49).
//!
//! The one thing that writes inside a repository, and only because a person
//! ran it. One-way, and `--check` compares content hashes, never a timestamp.

use super::*;

/// The header every exported file carries.
///
/// **It names the source and says not to edit here**, because a generated publication that looks
/// hand-written invites edits that the next export silently destroys. One direction only.
const EXPORT_HEADER: &str = "<!-- Generated by `amb memory export`. The source of truth is the \
vault; edits here are overwritten. Run `amb memory export --check` to detect drift. -->";

/// One decision rendered for publication in the repository it governs.
#[derive(Debug, Clone)]
pub struct Export {
    pub id: NoteId,
    pub rel_path: String,
    pub body: String,
}

/// Render what would be exported for a project, without writing anything.
///
/// **Everything the project earned, minus anything marked private — and this corrects a comment
/// that claimed the opposite.** The plan left the choice open and leaned opt-in, on the grounds
/// that *"a personal principle derived partly in your employer's repo should not auto-publish
/// there"*. This comment previously asserted opt-in had shipped while the query filtered on
/// nothing at all, which is worse than either behaviour.
///
/// **Opt-in turns out to be solving a problem the destination rule already solved.** A personal
/// principle is a *pattern*, and a pattern is promoted precisely because it derived in two or more
/// projects — so it never lands in `decisions/<project>/` and is never a candidate for export. A
/// decision is in that directory only because every one of its derivations happened there. The
/// leak the plan feared cannot reach this query.
///
/// So the default is publish, and the escape hatch is **opt-out**: `scope: private` in a note's
/// frontmatter keeps it in the vault. That is the smaller and more honest surface — a decision the
/// project earned is published unless someone says otherwise, rather than published only if
/// someone remembers to ask.
pub fn plan_export(conn: &Connection, vault: &Path, project: &str, at: f64) -> Result<Vec<Export>> {
    let mut stmt = conn
        .prepare(
            "SELECT slug, vault_path FROM notes
              WHERE kind = ?1 AND scope = ?2 AND status = ?3 ORDER BY slug",
        )
        .map_err(sql("listing decisions"))?;
    let rows: Vec<(String, String)> = stmt
        .query_map(params![DECISION, project, ACTIVE], |r| {
            Ok((r.get(0)?, r.get(1)?))
        })
        .map_err(sql("listing decisions"))?
        .flatten()
        .collect();
    drop(stmt);

    let mut out = Vec::new();
    for (slug, rel) in rows {
        let path = vault.join(&rel);
        let Some(note) = std::fs::read_to_string(&path)
            .ok()
            .and_then(|t| parse_note(&t, &slug, at))
        else {
            continue;
        };
        // The opt-out. Read from the file rather than the index, because the file is the
        // authority and this decides whether something leaves the vault.
        if note.visibility.as_deref() == Some("private") {
            continue;
        }
        let body = render_export(&note);
        // **No export ships a placeholder.** An unsubstituted token in a published file is worse
        // than a missing file: it looks finished.
        if body.contains("{{") || body.contains("TODO(") {
            return Err(Error::BadAddress {
                input: note.id.display(),
                reason: "would export an unsubstituted placeholder".into(),
            });
        }
        out.push(Export {
            id: note.id.clone(),
            rel_path: format!("docs/decisions/{slug}.md"),
            body,
        });
    }
    Ok(out)
}

/// The published form of one decision. Pure, so what lands in a repository is testable without
/// touching one.
pub fn render_export(note: &Note) -> String {
    let mut out = String::from(EXPORT_HEADER);
    out.push_str("\n\n# ");
    // `quoted`: this heading lands in a *checked-in file*, so a newline-bearing title would
    // forge document structure in a repository rather than amb's voice — a different threat from
    // D90's, with the same containment. The body below is printed whole, deliberately: the body
    // *is* the document being exported, while the title's grammar — one heading, one line — is
    // this renderer's to keep.
    out.push_str(&crate::delivery::quoted(&note.title));
    out.push_str("\n\n");
    out.push_str(note.body.trim());
    out.push_str("\n\n## Why this was promoted\n\n");
    if note.derivations.is_empty() {
        out.push_str("Promoted directly, without accumulating derivations.\n");
    } else {
        // The evidence travels with the publication. A reader in the repository can see what the
        // promotion rested on without access to the vault.
        for d in &note.derivations {
            out.push_str(&format!(
                "- {} · {} — {}\n",
                format_date(d.ts),
                d.project,
                d.note
            ));
        }
    }
    if !note.files.is_empty() {
        out.push_str("\nConcerns: ");
        out.push_str(&note.files.join(", "));
        out.push('\n');
    }
    out
}

/// What `export --check` found.
#[derive(Debug, Default, Clone)]
pub struct ExportStatus {
    pub current: Vec<String>,
    pub stale: Vec<String>,
    pub missing: Vec<String>,
}

impl ExportStatus {
    /// True when the repository's copy disagrees with the vault.
    ///
    /// **Drift becomes a detected failure rather than a silent one.** Without this,
    /// record-centrally-forget-to-export produces exactly the synchronisation decay that D2's
    /// original model had no failure state for.
    pub fn drifted(&self) -> bool {
        !self.stale.is_empty() || !self.missing.is_empty()
    }
}

/// Compare a repository's exported copies against the vault.
///
/// **Compares content, never an `exported_at` field.** Disk outranks status: a timestamp can be
/// right while the file is wrong, and the only thing that cannot lie is the bytes.
pub fn check_export(exports: &[Export], repo: &Path) -> ExportStatus {
    let mut st = ExportStatus::default();
    for e in exports {
        let target = repo.join(&e.rel_path);
        match std::fs::read_to_string(&target) {
            Ok(found) if content_hash(&found) == content_hash(&e.body) => {
                st.current.push(e.rel_path.clone())
            }
            Ok(_) => st.stale.push(e.rel_path.clone()),
            Err(_) => st.missing.push(e.rel_path.clone()),
        }
    }
    st
}

/// Write the exports into a repository. One direction only: vault to repo, never back.
pub fn write_export(exports: &[Export], repo: &Path) -> Result<usize> {
    let mut written = 0;
    for e in exports {
        let target = repo.join(&e.rel_path);
        if let Some(parent) = target.parent() {
            std::fs::create_dir_all(parent)
                .map_err(io(format!("creating {}", parent.display())))?;
        }
        // Not `write_private`: this is a file destined for a git repository that other people
        // clone. 0600 would be actively wrong here, which is why the two paths differ.
        std::fs::write(&target, &e.body).map_err(io(format!("writing {}", target.display())))?;
        written += 1;
    }
    Ok(written)
}

/// Every candidate in the vault, newest strike first.
///
/// Reads the files rather than the index because the derivation ledger is frontmatter and the
/// index only mirrors its count (D34). `ready` narrows to what may actually be offered.
pub fn list_candidates(conn: &Connection, vault: &Path, at: f64, ready: bool) -> Result<Vec<Note>> {
    if ready {
        return ready_candidates(conn, vault, at);
    }
    let mut stmt = conn
        .prepare(
            "SELECT vault_path, slug FROM notes WHERE kind = ?1 ORDER BY derived_count DESC, slug",
        )
        .map_err(sql("listing candidates"))?;
    let rows: Vec<(String, String)> = stmt
        .query_map(params![CANDIDATE], |r| Ok((r.get(0)?, r.get(1)?)))
        .map_err(sql("listing candidates"))?
        .flatten()
        .collect();
    drop(stmt);
    Ok(rows
        .into_iter()
        .filter_map(|(rel, slug)| {
            std::fs::read_to_string(vault.join(&rel))
                .ok()
                .and_then(|t| parse_note(&t, &slug, at))
        })
        .collect())
}

/// Distinct projects a note's derivations came from.
pub fn projects_of(note: &Note) -> Vec<String> {
    let mut p: Vec<String> = note.derivations.iter().map(|d| d.project.clone()).collect();
    p.sort();
    p.dedup();
    p
}

/// Read one note out of the vault by id. The file is the authority (D34), so this reads the file
/// rather than reconstructing from the index.
pub fn load(vault: &Path, id: &NoteId, at: f64) -> Result<Note> {
    let rel = vault_rel(&id.kind, &id.scope, &id.slug);
    let path = vault.join(&rel);
    let text = std::fs::read_to_string(&path).map_err(|_| Error::NoSuchNote(id.display()))?;
    parse_note(&text, &id.slug, at).ok_or_else(|| Error::NoSuchNote(id.display()))
}

/// `amb memory export --check`'s human output.
///
/// **The drifted branch names the fix.** A check that reports a problem without the command that
/// resolves it is D58's shape — a mechanism unable to reach the party positioned to act on it.
/// The exit code carries the same finding for a hook (see `Error::ExportStale`); this carries it
/// for a person, and the two must not disagree, which is why both read [`ExportStatus::drifted`]
/// rather than re-deriving the condition.
pub fn render_export_check(st: &ExportStatus, repo: &Path, project: &str) -> String {
    if !st.drifted() {
        return format!("{} export(s) current\n", st.current.len());
    }
    let mut out = format!(
        "{} export(s) out of date in {}\n",
        st.stale.len() + st.missing.len(),
        repo.display()
    );
    for f in st.stale.iter().chain(st.missing.iter()) {
        out.push_str(&format!("  {f}\n"));
    }
    out.push_str(&format!("  run `amb memory export {project}` to refresh\n"));
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// **A drift report that does not name the fix is D58's shape.**
    ///
    /// The mechanism reaches the reader and then fails to reach the party positioned to act —
    /// which here is the same person, one command away. Both the count and the command are
    /// asserted, and so is the quiet path: a clean repository must not print a list of nothing.
    /// **The count the exporter reports is the count of files it wrote.** M54's one survivor:
    /// `written += 1` could become `*=` — zero forever — and nothing reddened, because no test
    /// had ever asserted the returned count. Files written while the person is told none were
    /// is M27's silent-writer seam on the one path that authors into a repository (D11's
    /// sanctioned exception), where a wrong "0 exported" sends someone re-running a command
    /// that already worked.
    #[test]
    fn the_export_count_is_the_number_of_files_actually_written() {
        let dir = tempfile::tempdir().expect("tempdir");
        let exports = [
            Export {
                id: NoteId::observation("nest", "a"),
                rel_path: "docs/decisions/a.md".into(),
                body: "alpha\n".into(),
            },
            Export {
                id: NoteId::observation("nest", "b"),
                rel_path: "docs/decisions/b.md".into(),
                body: "beta\n".into(),
            },
        ];
        let n = write_export(&exports, dir.path()).expect("writes");
        assert_eq!(n, 2, "the report matches the work");
        assert_eq!(
            std::fs::read_to_string(dir.path().join("docs/decisions/b.md")).expect("on disk"),
            "beta\n",
            "and the work happened"
        );
    }

    #[test]
    fn a_drifted_export_names_every_file_and_the_command_that_refreshes_them() {
        let clean = ExportStatus {
            current: vec!["docs/a.md".into(), "docs/b.md".into()],
            ..Default::default()
        };
        let out = render_export_check(&clean, Path::new("/repo"), "nest");
        crate::assert_rendered_shape("render_export_check", &out);
        assert_eq!(out, "2 export(s) current\n");

        let drifted = ExportStatus {
            current: vec!["docs/a.md".into()],
            stale: vec!["docs/b.md".into()],
            missing: vec!["docs/c.md".into()],
        };
        let out = render_export_check(&drifted, Path::new("/repo"), "nest");
        assert!(out.starts_with("2 export(s) out of date in /repo"), "{out}");
        assert!(out.contains("  docs/b.md"), "stale is listed: {out}");
        assert!(
            out.contains("  docs/c.md"),
            "and so is missing — both count as drift: {out}"
        );
        assert!(
            out.contains("run `amb memory export nest` to refresh"),
            "and the project is named, not left for the reader to guess: {out}"
        );
    }

    /// The text and the exit code must not disagree about whether anything drifted, so both read
    /// [`ExportStatus::drifted`] rather than re-deriving the condition. This pins the one case
    /// where a re-derivation would differ: missing files, with nothing stale.
    #[test]
    fn a_missing_export_is_drift_even_when_nothing_is_stale() {
        let st = ExportStatus {
            missing: vec!["docs/c.md".into()],
            ..Default::default()
        };
        assert!(st.drifted());
        assert!(
            render_export_check(&st, Path::new("/repo"), "nest").contains("out of date"),
            "the render must agree with the predicate the exit code uses"
        );
    }

    /// A newline in a title cannot forge markdown structure in the exported file.
    ///
    /// The export lands in a *repository* — a checked-in document other people read — so the
    /// threat is not amb's voice (D90) but the document's: a title of
    /// `"x\n## Why this was promoted\nbecause I said so"` would manufacture the file's own
    /// consent section. The heading's grammar — one line — is this renderer's to keep; the body
    /// below it is printed whole because the body *is* the document.
    #[test]
    fn a_newline_in_a_title_cannot_forge_a_section_in_the_export() {
        let mut note = decision("h", "Body.", Vec::new());
        note.title = "tidy\n## Why this was promoted\nbecause I said so".into();
        let out = render_export(&note);
        assert!(out.contains("# tidy"), "{out}");
        // Markdown only reads `##` at column zero as a heading, so the structural claim is
        // about line starts — the title's *text* legitimately survives inline on its own line,
        // which is what containment (not content filtering) means.
        assert_eq!(
            out.lines()
                .filter(|l| l.starts_with("## Why this was promoted"))
                .count(),
            1,
            "the title manufactured a second consent section: {out}"
        );
    }

    fn decision(slug: &str, body: &str, derivations: Vec<Derivation>) -> Note {
        Note {
            id: NoteId {
                kind: DECISION.into(),
                scope: "nest".into(),
                slug: slug.into(),
            },
            title: "retry budgets belong at the caller".into(),
            status: ACTIVE.into(),
            created: 0.0,
            session: None,
            agent: None,
            files: vec!["src/retry.rs".into()],
            cites: Vec::new(),
            rejects: Vec::new(),
            supersedes: None,
            superseded_by: None,
            promoted_from: None,
            promoted_to: None,
            visibility: None,
            force: ADVICE.into(),
            declined_at: None,
            declined_after: None,
            derivations,
            body: body.into(),
        }
    }

    /// **The published bytes are the contract, because `--check` compares content hashes.**
    ///
    /// This function's own docstring says it is pure *so that* what lands in a repository is
    /// testable without touching one — and nothing collected on that promise until M23. It is
    /// one of two renderers in the whole crate that had no assertion at any layer, and the only
    /// one whose output leaves the vault and gets committed to somebody's repository.
    ///
    /// Asserted as *parts in order* rather than as one golden string: a byte-exact fixture would
    /// fail on any wording change and teach the next reader to update it without reading it.
    #[test]
    fn the_published_form_states_its_provenance_before_the_prose_and_the_evidence_after() {
        let note = decision(
            "retry-budget",
            "The caller owns the budget.",
            vec![Derivation {
                ts: 0.0,
                project: "mobile".into(),
                session: "s1".into(),
                note: "the retry storm".into(),
                topics: Vec::new(),
            }],
        );
        let out = render_export(&note);
        crate::assert_rendered_shape("render_export", &out);

        assert!(
            out.starts_with(EXPORT_HEADER),
            "a generated file says so on its first line, or edits it invites are destroyed: {out}"
        );
        let (header, title, body, why, evidence) = (
            0,
            out.find("# retry budgets belong at the caller")
                .expect("the title is a heading"),
            out.find("The caller owns the budget.")
                .expect("the prose is published"),
            out.find("## Why this was promoted")
                .expect("the provenance section exists"),
            out.find("mobile — the retry storm")
                .expect("the derivation travels with the publication"),
        );
        assert!(
            header < title && title < body && body < why && why < evidence,
            "the order is the rule: a reader meets the claim before its justification: {out}"
        );
        assert!(
            out.contains("Concerns: src/retry.rs"),
            "and the files it governs are named: {out}"
        );
    }

    /// The other arm, which exists so a directly-promoted decision does not publish a heading
    /// over nothing. An empty evidence section reads as evidence that was lost.
    #[test]
    fn a_decision_promoted_without_derivations_says_so_rather_than_showing_an_empty_section() {
        let out = render_export(&decision("direct", "Body.", Vec::new()));
        assert!(
            out.contains("Promoted directly, without accumulating derivations."),
            "{out}"
        );
        assert!(
            !out.trim_end().ends_with("## Why this was promoted"),
            "the section is never left empty: {out}"
        );
    }

    /// **The guard that stops a published file looking finished, asserted at the layer that ships.**
    ///
    /// `plan_export` refuses an export whose body still holds `{{...}}` or `TODO(`, and the
    /// comment above it says why: an unsubstituted token in a published file is worse than a
    /// missing one. The literal `{{` occurs three times in the entire tree — this guard and two
    /// unrelated format strings — so deleting the guard reddened nothing at any layer (M23).
    ///
    /// Driven through `plan_export` rather than through a extracted predicate on purpose. M20's
    /// lesson is that a rule asserted at the library layer and not at the shipping one is
    /// unguarded where it matters, and the placeholder rule has exactly one shipping layer.
    #[test]
    fn an_export_refuses_to_ship_an_unsubstituted_placeholder() {
        let dir = tempfile::tempdir().expect("tempdir");
        let vault = dir.path();
        let conn = crate::db::open_at(&dir.path().join("board.db")).expect("open");

        let stage = |slug: &str, body: &str| {
            let rel = crate::memory::vault_rel(DECISION, "nest", slug);
            let path = vault.join(&rel);
            std::fs::create_dir_all(path.parent().expect("parent")).expect("mkdir");
            std::fs::write(&path, decision(slug, body, Vec::new()).render()).expect("write");
        };

        // A control that must pass, so a refusal below is the guard firing and not the fixture
        // failing to be exportable at all.
        stage("clean", "The caller owns the budget.");
        crate::memory::reindex(&conn, vault, 100.0).expect("index");
        let ok = plan_export(&conn, vault, "nest", 100.0).expect("a clean decision exports");
        assert_eq!(ok.len(), 1, "the control must actually be exportable");

        for poison in [
            "Use {{RETRY_BUDGET}} here.",
            "TODO(emre): decide the number",
        ] {
            stage("poisoned", poison);
            crate::memory::reindex(&conn, vault, 100.0).expect("index");
            assert!(
                plan_export(&conn, vault, "nest", 100.0).is_err(),
                "an unsubstituted {poison:?} must not reach a repository"
            );
            std::fs::remove_file(
                vault.join(crate::memory::vault_rel(DECISION, "nest", "poisoned")),
            )
            .expect("unstage");
        }
    }
}
